[versions]
java = "17"
kotlin = "2.3.0"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version = "6.0.2" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }

[plugins]
dokka = { id = "org.jetbrains.dokka-javadoc", version = "2.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
jacoco-testkit = { id = "io.github.gmazzo.gradle.testkit.jacoco", version = "1.0.5" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
